#!/bin/bash -l
#SBATCH --nodes=4
#SBATCH --tasks-per-node=20
#SBATCH --partition=<PARTITION>
#SBATCH --time=<WALL>:00:00
#SBATCH --job-name=<JOBNAME>
#SBATCH --mail-user=<EMAIL>
#SBATCH --output=./out.out
#SBATCH --error=./out.err

#### do not export environment variables
unset SLURM_EXPORT_ENV
## jobs always start in submit directory

<OMPSECTION>

export GMON_OUT_PREFIX=./gmon

ulimit -s unlimited
#ulimit -c unlimited
#ulimit -s unlimited
#ulimit -d unlimited
#ulimit -m unlimited
ulimit -v unlimited
#ulimit -f unlimited
ulimit -a

#load required modules (compiler, MPI, ...)
module purge
module load intel64
module load intelmpi
module load netcdf

# Run the job
srun <CMD> 
